// Code generated by tygo. DO NOT EDIT.
import { MessageData } from './message.gen';
type StringIndexable = Record<string, unknown>;

//////////
// source: data.go

export const MaxInternalEventPayloadBytes = 64 * 1024;
/**
 * The minimum interval (in seconds) allowed for an interval schedule. This caps
 * how fast a schedule can burn credits — see the billing rationale in the plan.
 */
export const ScheduleMinIntervalSeconds = 60;
export interface FlowData {
  nodes: FlowNode[];
  edges: FlowEdge[];
}
export type FlowNodeType = string;
export const FlowNodeTypeEntryCommand: FlowNodeType = "entry_command";
export const FlowNodeTypeEntryEvent: FlowNodeType = "entry_event";
export const FlowNodeTypeEntryComponentButton: FlowNodeType = "entry_component_button";
export const FlowNodeTypeEntrySchedule: FlowNodeType = "entry_schedule";
export const FlowNodeTypeEntryCustomEvent: FlowNodeType = "entry_custom_event";
export const FlowNodeTypeOptionCommandArgument: FlowNodeType = "option_command_argument";
export const FlowNodeTypeOptionCommandPermissions: FlowNodeType = "option_command_permissions";
export const FlowNodeTypeOptionCommandBotPermissions: FlowNodeType = "option_command_bot_permissions";
export const FlowNodeTypeOptionCommandContexts: FlowNodeType = "option_command_contexts";
export const FlowNodeTypeOptionEventFilter: FlowNodeType = "option_event_filter";
export const FlowNodeTypeActionResponseCreate: FlowNodeType = "action_response_create";
export const FlowNodeTypeActionResponseEdit: FlowNodeType = "action_response_edit";
export const FlowNodeTypeActionResponseDelete: FlowNodeType = "action_response_delete";
export const FlowNodeTypeActionResponseDefer: FlowNodeType = "action_response_defer";
export const FlowNodeTypeActionMessageCreate: FlowNodeType = "action_message_create";
export const FlowNodeTypeActionMessageEdit: FlowNodeType = "action_message_edit";
export const FlowNodeTypeActionMessageDelete: FlowNodeType = "action_message_delete";
export const FlowNodeTypeActionPrivateMessageCreate: FlowNodeType = "action_private_message_create";
export const FlowNodeTypeActionMessageReactionCreate: FlowNodeType = "action_message_reaction_create";
export const FlowNodeTypeActionMessageReactionDelete: FlowNodeType = "action_message_reaction_delete";
export const FlowNodeTypeActionMemberBan: FlowNodeType = "action_member_ban";
export const FlowNodeTypeActionMemberUnban: FlowNodeType = "action_member_unban";
export const FlowNodeTypeActionMemberKick: FlowNodeType = "action_member_kick";
export const FlowNodeTypeActionMemberTimeout: FlowNodeType = "action_member_timeout";
export const FlowNodeTypeActionMemberEdit: FlowNodeType = "action_member_edit";
export const FlowNodeTypeActionMemberRoleAdd: FlowNodeType = "action_member_role_add";
export const FlowNodeTypeActionMemberRoleRemove: FlowNodeType = "action_member_role_remove";
export const FlowNodeTypeActionMemberGet: FlowNodeType = "action_member_get";
export const FlowNodeTypeActionMemberVoiceMove: FlowNodeType = "action_member_voice_move";
export const FlowNodeTypeActionMemberVoiceDisconnect: FlowNodeType = "action_member_voice_disconnect";
export const FlowNodeTypeActionMemberVoiceMute: FlowNodeType = "action_member_voice_mute";
export const FlowNodeTypeActionMemberVoiceDeafen: FlowNodeType = "action_member_voice_deafen";
export const FlowNodeTypeActionUserGet: FlowNodeType = "action_user_get";
export const FlowNodeTypeActionChannelGet: FlowNodeType = "action_channel_get";
export const FlowNodeTypeActionChannelCreate: FlowNodeType = "action_channel_create";
export const FlowNodeTypeActionChannelEdit: FlowNodeType = "action_channel_edit";
export const FlowNodeTypeActionChannelDelete: FlowNodeType = "action_channel_delete";
export const FlowNodeTypeActionThreadCreate: FlowNodeType = "action_thread_create";
export const FlowNodeTypeActionThreadMemberAdd: FlowNodeType = "action_thread_member_add";
export const FlowNodeTypeActionThreadMemberRemove: FlowNodeType = "action_thread_member_remove";
export const FlowNodeTypeActionForumPostCreate: FlowNodeType = "action_forum_post_create";
export const FlowNodeTypeActionRoleGet: FlowNodeType = "action_role_get";
export const FlowNodeTypeActionRoleCreate: FlowNodeType = "action_role_create";
export const FlowNodeTypeActionRoleEdit: FlowNodeType = "action_role_edit";
export const FlowNodeTypeActionRoleDelete: FlowNodeType = "action_role_delete";
export const FlowNodeTypeActionGuildGet: FlowNodeType = "action_guild_get";
export const FlowNodeTypeActionMessageGet: FlowNodeType = "action_message_get";
export const FlowNodeTypeActionHTTPRequest: FlowNodeType = "action_http_request";
export const FlowNodeTypeActionAIChatCompletion: FlowNodeType = "action_ai_chat_completion";
export const FlowNodeTypeActionAISearchWeb: FlowNodeType = "action_ai_web_search";
export const FlowNodeTypeActionExpressionEvaluate: FlowNodeType = "action_expression_evaluate";
export const FlowNodeTypeActionRandomGenerate: FlowNodeType = "action_random_generate";
export const FlowNodeTypeActionLog: FlowNodeType = "action_log";
export const FlowNodeTypeActionVariableSet: FlowNodeType = "action_variable_set";
export const FlowNodeTypeActionVariableDelete: FlowNodeType = "action_variable_delete";
export const FlowNodeTypeActionVariableGet: FlowNodeType = "action_variable_get";
export const FlowNodeTypeActionBalanceGet: FlowNodeType = "action_balance_get";
export const FlowNodeTypeActionBalanceAdd: FlowNodeType = "action_balance_add";
export const FlowNodeTypeActionBalanceRemove: FlowNodeType = "action_balance_remove";
export const FlowNodeTypeActionBalanceSet: FlowNodeType = "action_balance_set";
export const FlowNodeTypeActionBalanceTransfer: FlowNodeType = "action_balance_transfer";
export const FlowNodeTypeActionBalanceLeaderboard: FlowNodeType = "action_balance_leaderboard";
export const FlowNodeTypeActionTimeNow: FlowNodeType = "action_time_now";
export const FlowNodeTypeActionListPick: FlowNodeType = "action_list_pick";
export const FlowNodeTypeActionTextTransform: FlowNodeType = "action_text_transform";
export const FlowNodeTypeActionJSONParse: FlowNodeType = "action_json_parse";
export const FlowNodeTypeActionJSONBuild: FlowNodeType = "action_json_build";
export const FlowNodeTypeActionCooldownCheck: FlowNodeType = "action_cooldown_check";
export const FlowNodeTypeActionNumberFormat: FlowNodeType = "action_number_format";
export const FlowNodeTypeActionListFormat: FlowNodeType = "action_list_format";
export const FlowNodeTypeActionListJoin: FlowNodeType = "action_list_join";
export const FlowNodeTypeActionListLength: FlowNodeType = "action_list_length";
export const FlowNodeTypeActionListSort: FlowNodeType = "action_list_sort";
export const FlowNodeTypeActionListReverse: FlowNodeType = "action_list_reverse";
export const FlowNodeTypeActionRegexMatch: FlowNodeType = "action_regex_match";
export const FlowNodeTypeActionTimeMath: FlowNodeType = "action_time_math";
export const FlowNodeTypeActionTimeDiff: FlowNodeType = "action_time_diff";
export const FlowNodeTypeActionMessagePin: FlowNodeType = "action_message_pin";
export const FlowNodeTypeActionMessageUnpin: FlowNodeType = "action_message_unpin";
export const FlowNodeTypeActionMessagePurge: FlowNodeType = "action_message_purge";
export const FlowNodeTypeActionChannelSlowmode: FlowNodeType = "action_channel_slowmode";
export const FlowNodeTypeActionQRCreate: FlowNodeType = "action_qr_create";
export const FlowNodeTypeActionEventEmit: FlowNodeType = "action_event_emit";
export const FlowNodeTypeActionTableInsert: FlowNodeType = "action_table_insert";
export const FlowNodeTypeActionTableFindOne: FlowNodeType = "action_table_find_one";
export const FlowNodeTypeActionTableQuery: FlowNodeType = "action_table_query";
export const FlowNodeTypeActionTableUpdate: FlowNodeType = "action_table_update";
export const FlowNodeTypeActionTableDelete: FlowNodeType = "action_table_delete";
export const FlowNodeTypeControlConditionCompare: FlowNodeType = "control_condition_compare";
export const FlowNodeTypeControlConditionItemCompare: FlowNodeType = "control_condition_item_compare";
export const FlowNodeTypeControlConditionUser: FlowNodeType = "control_condition_user";
export const FlowNodeTypeControlConditionItemUser: FlowNodeType = "control_condition_item_user";
export const FlowNodeTypeControlConditionChannel: FlowNodeType = "control_condition_channel";
export const FlowNodeTypeControlConditionItemChannel: FlowNodeType = "control_condition_item_channel";
export const FlowNodeTypeControlConditionRole: FlowNodeType = "control_condition_role";
export const FlowNodeTypeControlConditionItemRole: FlowNodeType = "control_condition_item_role";
export const FlowNodeTypeControlConditionItemElse: FlowNodeType = "control_condition_item_else";
export const FlowNodeTypeControlErrorHandler: FlowNodeType = "control_error_handler";
export const FlowNodeTypeControlLoop: FlowNodeType = "control_loop";
export const FlowNodeTypeControlLoopEach: FlowNodeType = "control_loop_each";
export const FlowNodeTypeControlLoopEnd: FlowNodeType = "control_loop_end";
export const FlowNodeTypeControlLoopExit: FlowNodeType = "control_loop_exit";
export const FlowNodeTypeControlSleep: FlowNodeType = "control_sleep";
export const FlowNodeTypeSuspendResponseModal: FlowNodeType = "suspend_response_modal";
export interface FlowNode {
  id: string;
  type?: FlowNodeType;
  data: FlowNodeData & StringIndexable;
  position: FlowNodePosition;
}
export interface FlowTableFilter {
  column_id: string;
  operator: string;
  value?: any;
}
export interface FlowTableSort {
  column_id: string;
  direction: string;
}
export interface FlowTableMutation {
  column_id: string;
  operation: string;
  value?: any;
}
export interface FlowNodeData {
  /**
   * Shared
   */
  name?: string;
  description?: string;
  custom_label?: string;
  audit_log_reason?: string;
  /**
   * Temporary Variables
   */
  temporary_name?: string;
  /**
   * Command Argument
   */
  command_argument_type?: CommandArgumentType;
  command_argument_required?: boolean;
  command_argument_choices?: CommandArgumentChoiceData[];
  command_argument_min_value?: number /* float64 */;
  command_argument_max_value?: number /* float64 */;
  command_argument_max_length?: number /* int */;
  /**
   * Command trigger types (on the entry_command node). For backwards
   * compatibility the absence of these means: slash enabled, prefix disabled.
   */
  command_disable_slash?: boolean;
  command_enable_prefix?: boolean;
  /**
   * Command Permissions — the permissions the invoking USER must have. This is
   * enforced by Discord itself via DefaultMemberPermissions on the command.
   */
  command_permissions?: string;
  /**
   * Command Bot Permissions — the permissions the BOT must hold in the
   * invocation channel for the command to run. Unlike CommandPermissions,
   * Discord does not enforce this, so it is checked at runtime before the flow
   * executes; when the bot is missing a permission the invoker is told and the
   * flow is skipped. Stored as a decimal permission bitmask string.
   */
  command_bot_permissions?: string;
  /**
   * Command Contexts
   */
  command_disabled_contexts?: CommandContextType[];
  /**
   * Command Installations
   */
  command_disabled_integrations?: CommandDisabledIntegrationType[];
  /**
   * Guild Get
   */
  guild_target?: string;
  /**
   * Message & Response Create, Edit, Delete
   */
  message_target?: string;
  message_data?: MessageData;
  message_template_id?: string;
  message_ephemeral?: boolean;
  /**
   * Message Reaction Create, Delete
   */
  emoji_data?: EmojiData;
  /**
   * Modal
   */
  modal_data?: ModalData;
  /**
   * Member Voice Mute / Deafen
   */
  member_voice_mute?: boolean;
  member_voice_deafen?: boolean;
  /**
   * Member Ban, Kick, Timeout, Edit, Get
   */
  user_target?: string;
  member_ban_delete_message_duration_seconds?: string;
  member_timeout_duration_seconds?: string;
  member_data?: MemberData;
  /**
   * Channel Create, Edit, Delete, Get
   */
  channel_target?: string;
  channel_data?: ChannelData;
  /**
   * Role Create, Edit, Delete, Get
   */
  role_target?: string;
  role_data?: RoleData;
  /**
   * Variable Set, Delete
   */
  variable_id?: string;
  variable_scope?: string;
  variable_value?: string;
  variable_operation?: any /* provider.VariableOperation */;
  /**
   * Economy Balance Get, Add, Remove, Set, Transfer, Leaderboard
   * (the currency is the variable_id field above)
   */
  economy_user_target?: string; // template resolving to the scope (usually a user id)
  economy_recipient?: string; // template resolving to the recipient scope (transfer)
  economy_amount?: string; // template resolving to the amount
  economy_limit?: string; // template resolving to the leaderboard size
  economy_allow_negative?: boolean; // allow balances to drop below zero
  /**
   * Time Now (TimeFormat/TimeTimezone are also reused by Time Math output)
   */
  time_format?: string; // unix | unix_ms | iso | date | time | datetime | custom Go layout
  time_timezone?: string; // IANA timezone name, empty = UTC
  /**
   * Time Math / Diff
   */
  time_input?: string; // template resolving to a unix timestamp or RFC3339 string
  time_amount?: string; // template resolving to the amount to add/subtract
  time_unit?: string; // s | m | h | d (shared by math and diff)
  time_op?: string; // add | sub
  time_a?: string; // diff: first timestamp
  time_b?: string; // diff: second timestamp (result is b - a in TimeUnit)
  /**
   * List Pick
   */
  list_pick_input?: string; // template resolving to a list
  /**
   * Number Format
   */
  number_input?: string; // template resolving to a number
  number_style?: string; // thousands | compact | decimal
  number_decimals?: string; // template resolving to the decimal places
  /**
   * List Format / Join / Length / Sort / Reverse
   */
  list_input?: string; // template resolving to a list
  list_item_template?: string; // per-item template, with {{item}} and {{index}} bound
  list_joiner?: string; // separator template, default newline
  list_sort_order?: string; // asc | desc
  /**
   * Message Purge / Channel Slowmode (pin/unpin reuse channel_target + message_target)
   */
  message_purge_count?: string; // template resolving to how many messages to delete
  channel_slowmode_seconds?: string; // template resolving to the slowmode in seconds
  /**
   * Text Transform (TextInput is also reused as the Regex Match source text)
   */
  text_input?: string; // template resolving to the source text
  text_operation?: string; // upper | lower | trim | length | replace | split
  text_arg1?: string; // replace: search, split: separator
  text_arg2?: string; // replace: replacement
  /**
   * Regex Match (uses TextInput as the source text)
   */
  regex_pattern?: string; // template resolving to the regex pattern
  regex_flags?: string; // any of i (case-insensitive), m (multiline), s (dotall)
  /**
   * JSON Parse / Build
   */
  json_input?: string; // parse: JSON string to decode; build: value to encode
  /**
   * Cooldown Check (stores the last-use unix timestamp in the variable_id above)
   */
  cooldown_scope?: string; // template resolving to the scope, default {{user.id}}
  cooldown_duration?: string; // template resolving to the cooldown length in seconds
  cooldown_peek?: boolean; // only check, don't reset the cooldown
  /**
   * HTTP Request
   */
  http_request_data?: HTTPRequestData;
  /**
   * AI Chat Completion
   */
  ai_chat_completion_data?: AIChatCompletionData;
  /**
   * Random Generate
   */
  random_min?: string;
  random_max?: string;
  /**
   * Event Entry
   */
  event_type?: string;
  /**
   * Custom internal event subscriber/publisher configuration.
   */
  custom_event_id?: string;
  event_payload?: { [key: string]: any};
  event_execution_mode?: any /* provider.InternalEventExecutionMode */;
  event_filter?: string;
  /**
   * Custom structured table actions. IDs are stable registry references;
   * values may contain templates and are evaluated immediately before access.
   */
  custom_table_id?: string;
  table_scope_id?: string;
  table_fields?: { [key: string]: any};
  table_filter_mode?: string;
  table_filters?: FlowTableFilter[];
  table_sort?: FlowTableSort[];
  table_limit?: number /* int */;
  table_offset?: number /* int */;
  table_updates?: FlowTableMutation[];
  /**
   * Schedule Entry (on the entry_schedule node). ScheduleType selects the
   * preset; the backend normalizes it to an interval or a cron expression via
   * CompiledFlowNode.ScheduleSpec().
   */
  schedule_type?: string; // interval | daily | weekly | cron
  schedule_interval_seconds?: number /* int */; // interval: seconds between runs (min 60)
  schedule_time?: string; // daily/weekly: "HH:MM" (24h)
  schedule_weekdays?: number /* int */[]; // weekly: 0-6 (Sunday=0)
  schedule_cron_expression?: string; // cron: standard 5-field expression
  schedule_timezone?: string; // IANA timezone, empty = Asia/Ho_Chi_Minh
  /**
   * Event Filter
   */
  event_filter_target?: EventFilterTarget;
  event_filter_mode?: ComparsionMode;
  event_filter_value?: string;
  /**
   * Log
   */
  log_level?: any /* provider.LogLevel */;
  log_message?: string;
  /**
   * Expression Evaluate
   */
  expression?: string;
  /**
   * Condition
   */
  condition_base_value?: string;
  condition_allow_multiple?: boolean;
  condition_item_mode?: ComparsionMode;
  condition_item_value?: string;
  /**
   * Loop
   */
  loop_count?: string;
  /**
   * Sleep
   */
  sleep_duration_seconds?: string;
  /**
   * QR Code Create (VietQR — https://vietqr.app/img). Builds an image URL.
   */
  qr_bank?: string; // bank code or short_name (required), e.g. "VCB"
  qr_account?: string; // account number (required), template
  qr_amount?: string; // transfer amount, template
  qr_description?: string; // transfer content, template
  qr_template?: string; // "" | compact | qronly | standee
  qr_holder?: string; // account holder name, template
  qr_store?: string; // store / company name, template
  qr_hide_info?: boolean; // when true sends showinfo=false (default VietQR shows info)
  qr_full_account?: boolean; // when true sends fullacc=true (show full account number)
}
export type ComparsionMode = string;
export const ComparsionModeEqual: ComparsionMode = "equal";
export const ComparsionModeNotEqual: ComparsionMode = "not_equal";
export const ComparsionModeGreaterThan: ComparsionMode = "greater_than";
export const ComparsionModeGreaterThanOrEqual: ComparsionMode = "greater_than_or_equal";
export const ComparsionModeLessThan: ComparsionMode = "less_than";
export const ComparsionModeLessThanOrEqual: ComparsionMode = "less_than_or_equal";
export const ComparsionModeContains: ComparsionMode = "contains";
export const ComparsionModeStartsWith: ComparsionMode = "starts_with";
export const ComparsionModeEndsWith: ComparsionMode = "ends_with";
/**
 * User condition
 */
export const ComparsionModeHasRole: ComparsionMode = "has_role";
export const ComparsionModeNotHasRole: ComparsionMode = "not_has_role";
export const ComparsionModeHasPermission: ComparsionMode = "has_permission";
export const ComparsionModeNotHasPermission: ComparsionMode = "not_has_permission";
export type CommandArgumentType = string;
export const CommandArgumentTypeString: CommandArgumentType = "string";
export const CommandArgumentTypeInteger: CommandArgumentType = "integer";
export const CommandArgumentTypeBoolean: CommandArgumentType = "boolean";
export const CommandArgumentTypeUser: CommandArgumentType = "user";
export const CommandArgumentTypeRole: CommandArgumentType = "role";
export const CommandArgumentTypeChannel: CommandArgumentType = "channel";
export const CommandArgumentTypeMentionable: CommandArgumentType = "mentionable";
export const CommandArgumentTypeNumber: CommandArgumentType = "number";
export const CommandArgumentTypeAttachment: CommandArgumentType = "attachment";
export type CommandContextType = string;
export const CommandContextTypeGuild: CommandContextType = "guild";
export const CommandContextTypeBotDM: CommandContextType = "bot_dm";
export const CommandContextTypePrivateChannel: CommandContextType = "private_channel";
export type CommandDisabledIntegrationType = string;
export const CommandDisabledIntegrationTypeGuildInstall: CommandDisabledIntegrationType = "guild_install";
export const CommandDisabledIntegrationTypeUserInstall: CommandDisabledIntegrationType = "user_install";
export type EventFilterTarget = string;
export const EventFilterTypeMessageContent: EventFilterTarget = "message_content";
export const EventFilterTypeUserID: EventFilterTarget = "user_id";
export const EventFilterTypeGuildID: EventFilterTarget = "guild_id";
export const EventFilterTypeChannelID: EventFilterTarget = "channel_id";
export interface CommandArgumentChoiceData {
  name?: string;
  value?: string;
}
export interface ChannelData {
  name?: string;
  type?: number /* int */;
  topic?: string;
  nsfw?: boolean;
  parent?: string;
  bitrate?: string;
  user_limit?: string;
  position?: string;
  permission_overwrites?: PermissionOverwriteData[];
  /**
   * Thread specific
   */
  invitable?: boolean;
}
export interface PermissionOverwriteData {
  id?: string;
  type?: number /* int */;
  allow?: string;
  deny?: string;
}
export interface RoleData {
  name?: string;
  color?: number /* int */;
  hoist?: boolean;
  /**
   * Permissions is a decimal permission bitmask stored as a string (like
   * CommandPermissions) so large 64-bit bitmasks survive the JSON/JS number
   * round-trip without losing precision.
   */
  permissions?: string;
  mentionable?: boolean;
  /**
   * Position is kept for completeness but is not applied on create/edit:
   * reordering roles is a separate Discord endpoint (MoveRoles).
   */
  position?: number /* int */;
}
export interface MemberData {
  nick?: string;
}
export interface EmojiData {
  id?: string;
  /**
   * Name is the name of a custom emoji or the unicode of a standard emoji.
   */
  name?: string;
}
export interface ModalData {
  title?: string;
  components?: ModalComponentData[];
}
export interface ModalComponentData {
  custom_id?: string;
  style?: number /* int */;
  label?: string;
  min_length?: number /* int */;
  max_length?: number /* int */;
  required?: boolean;
  value?: string;
  placeholder?: string;
  components?: ModalComponentData[];
}
export interface HTTPRequestData {
  url?: string;
  method?: string;
  headers?: HTTPRequestDataKeyValue[];
  query?: HTTPRequestDataKeyValue[];
  body_json?: Record<string, any> | null;
}
export interface HTTPRequestDataKeyValue {
  key: string;
  value: string;
}
export interface AIChatCompletionData {
  model?: string;
  system_prompt?: string;
  prompt?: string;
  max_completion_tokens?: string;
}
export interface FlowNodePosition {
  x: number /* float64 */;
  y: number /* float64 */;
}
export interface FlowEdge {
  id: string;
  type?: string;
  source: string;
  target: string;
  sourceHandle?: null | string;
  targetHandle?: null | string;
}

//////////
// source: state.go

export interface FlowContextState {
  node_states: { [key: string]: FlowContextNodeState | undefined};
  temporaries: { [key: string]: any /* thing.Thing */};
}
export interface FlowContextNodeState {
  condition_base_value?: any /* thing.Thing */;
  condition_item_met?: boolean;
  result?: any /* thing.Thing */;
  loop_exited?: boolean;
}
