// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custom_events.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomEvent = `-- name: CreateCustomEvent :one
INSERT INTO custom_events (id, app_id, name, description, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, app_id, name, description, created_at, updated_at
`

type CreateCustomEventParams struct {
	ID          string
	AppID       string
	Name        string
	Description string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

func (q *Queries) CreateCustomEvent(ctx context.Context, arg CreateCustomEventParams) (CustomEvent, error) {
	row := q.db.QueryRow(ctx, createCustomEvent,
		arg.ID,
		arg.AppID,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CustomEvent
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomEvent = `-- name: DeleteCustomEvent :execrows
DELETE FROM custom_events WHERE id = $1
`

func (q *Queries) DeleteCustomEvent(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCustomEvent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCustomEvent = `-- name: GetCustomEvent :one
SELECT id, app_id, name, description, created_at, updated_at FROM custom_events WHERE id = $1
`

func (q *Queries) GetCustomEvent(ctx context.Context, id string) (CustomEvent, error) {
	row := q.db.QueryRow(ctx, getCustomEvent, id)
	var i CustomEvent
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomEventsByApp = `-- name: GetCustomEventsByApp :many
SELECT id, app_id, name, description, created_at, updated_at FROM custom_events WHERE app_id = $1 ORDER BY name ASC
`

func (q *Queries) GetCustomEventsByApp(ctx context.Context, appID string) ([]CustomEvent, error) {
	rows, err := q.db.Query(ctx, getCustomEventsByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomEvent
	for rows.Next() {
		var i CustomEvent
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomEvent = `-- name: UpdateCustomEvent :one
UPDATE custom_events
SET name = $2, description = $3, updated_at = $4
WHERE id = $1
RETURNING id, app_id, name, description, created_at, updated_at
`

type UpdateCustomEventParams struct {
	ID          string
	Name        string
	Description string
	UpdatedAt   pgtype.Timestamp
}

func (q *Queries) UpdateCustomEvent(ctx context.Context, arg UpdateCustomEventParams) (CustomEvent, error) {
	row := q.db.QueryRow(ctx, updateCustomEvent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
	)
	var i CustomEvent
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
