// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custom_tables.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomTable = `-- name: CreateCustomTable :one
INSERT INTO custom_tables (id, app_id, name, description, scope, schema, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, app_id, name, description, scope, schema, created_at, updated_at
`

type CreateCustomTableParams struct {
	ID          string
	AppID       string
	Name        string
	Description string
	Scope       string
	Schema      []byte
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

func (q *Queries) CreateCustomTable(ctx context.Context, arg CreateCustomTableParams) (CustomTable, error) {
	row := q.db.QueryRow(ctx, createCustomTable,
		arg.ID,
		arg.AppID,
		arg.Name,
		arg.Description,
		arg.Scope,
		arg.Schema,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CustomTable
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.Schema,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomTable = `-- name: DeleteCustomTable :execrows
DELETE FROM custom_tables WHERE id = $1
`

func (q *Queries) DeleteCustomTable(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCustomTable, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCustomTable = `-- name: GetCustomTable :one
SELECT id, app_id, name, description, scope, schema, created_at, updated_at FROM custom_tables WHERE id = $1
`

func (q *Queries) GetCustomTable(ctx context.Context, id string) (CustomTable, error) {
	row := q.db.QueryRow(ctx, getCustomTable, id)
	var i CustomTable
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.Schema,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomTablesByApp = `-- name: GetCustomTablesByApp :many
SELECT id, app_id, name, description, scope, schema, created_at, updated_at FROM custom_tables WHERE app_id = $1 ORDER BY name ASC
`

func (q *Queries) GetCustomTablesByApp(ctx context.Context, appID string) ([]CustomTable, error) {
	rows, err := q.db.Query(ctx, getCustomTablesByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomTable
	for rows.Next() {
		var i CustomTable
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Name,
			&i.Description,
			&i.Scope,
			&i.Schema,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomTable = `-- name: UpdateCustomTable :one
UPDATE custom_tables
SET name = $2, description = $3, scope = $4, schema = $5, updated_at = $6
WHERE id = $1
RETURNING id, app_id, name, description, scope, schema, created_at, updated_at
`

type UpdateCustomTableParams struct {
	ID          string
	Name        string
	Description string
	Scope       string
	Schema      []byte
	UpdatedAt   pgtype.Timestamp
}

func (q *Queries) UpdateCustomTable(ctx context.Context, arg UpdateCustomTableParams) (CustomTable, error) {
	row := q.db.QueryRow(ctx, updateCustomTable,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Scope,
		arg.Schema,
		arg.UpdatedAt,
	)
	var i CustomTable
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.Description,
		&i.Scope,
		&i.Schema,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
