// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimSchedule = `-- name: ClaimSchedule :execrows
UPDATE schedules SET
    next_run_at = $1,
    last_run_at = $2
WHERE id = $3
    AND enabled = TRUE
    AND next_run_at IS NOT NULL
    AND next_run_at <= $2
`

type ClaimScheduleParams struct {
	NextRunAt pgtype.Timestamp
	Now       pgtype.Timestamp
	ID        string
}

func (q *Queries) ClaimSchedule(ctx context.Context, arg ClaimScheduleParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimSchedule, arg.NextRunAt, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countSchedulesByApp = `-- name: CountSchedulesByApp :one
SELECT COUNT(*) FROM schedules WHERE app_id = $1
`

func (q *Queries) CountSchedulesByApp(ctx context.Context, appID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSchedulesByApp, appID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (
    id,
    app_id,
    module_id,
    creator_user_id,
    enabled,
    description,
    trigger_type,
    interval_seconds,
    cron_expression,
    timezone,
    next_run_at,
    last_run_at,
    flow_source,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) RETURNING id, app_id, module_id, creator_user_id, enabled, description, trigger_type, interval_seconds, cron_expression, timezone, next_run_at, last_run_at, flow_source, created_at, updated_at
`

type CreateScheduleParams struct {
	ID              string
	AppID           string
	ModuleID        pgtype.Text
	CreatorUserID   string
	Enabled         bool
	Description     string
	TriggerType     string
	IntervalSeconds int32
	CronExpression  string
	Timezone        string
	NextRunAt       pgtype.Timestamp
	LastRunAt       pgtype.Timestamp
	FlowSource      []byte
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.ID,
		arg.AppID,
		arg.ModuleID,
		arg.CreatorUserID,
		arg.Enabled,
		arg.Description,
		arg.TriggerType,
		arg.IntervalSeconds,
		arg.CronExpression,
		arg.Timezone,
		arg.NextRunAt,
		arg.LastRunAt,
		arg.FlowSource,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ModuleID,
		&i.CreatorUserID,
		&i.Enabled,
		&i.Description,
		&i.TriggerType,
		&i.IntervalSeconds,
		&i.CronExpression,
		&i.Timezone,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.FlowSource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules WHERE id = $1
`

func (q *Queries) DeleteSchedule(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSchedule, id)
	return err
}

const getDueSchedules = `-- name: GetDueSchedules :many
SELECT schedules.id, schedules.app_id, schedules.module_id, schedules.creator_user_id, schedules.enabled, schedules.description, schedules.trigger_type, schedules.interval_seconds, schedules.cron_expression, schedules.timezone, schedules.next_run_at, schedules.last_run_at, schedules.flow_source, schedules.created_at, schedules.updated_at FROM schedules
JOIN apps ON apps.id = schedules.app_id
WHERE schedules.enabled = TRUE
    AND apps.enabled = TRUE
    AND schedules.next_run_at IS NOT NULL
    AND schedules.next_run_at <= $1
`

type GetDueSchedulesRow struct {
	Schedule Schedule
}

func (q *Queries) GetDueSchedules(ctx context.Context, nextRunAt pgtype.Timestamp) ([]GetDueSchedulesRow, error) {
	rows, err := q.db.Query(ctx, getDueSchedules, nextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDueSchedulesRow
	for rows.Next() {
		var i GetDueSchedulesRow
		if err := rows.Scan(
			&i.Schedule.ID,
			&i.Schedule.AppID,
			&i.Schedule.ModuleID,
			&i.Schedule.CreatorUserID,
			&i.Schedule.Enabled,
			&i.Schedule.Description,
			&i.Schedule.TriggerType,
			&i.Schedule.IntervalSeconds,
			&i.Schedule.CronExpression,
			&i.Schedule.Timezone,
			&i.Schedule.NextRunAt,
			&i.Schedule.LastRunAt,
			&i.Schedule.FlowSource,
			&i.Schedule.CreatedAt,
			&i.Schedule.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, app_id, module_id, creator_user_id, enabled, description, trigger_type, interval_seconds, cron_expression, timezone, next_run_at, last_run_at, flow_source, created_at, updated_at FROM schedules WHERE id = $1
`

func (q *Queries) GetSchedule(ctx context.Context, id string) (Schedule, error) {
	row := q.db.QueryRow(ctx, getSchedule, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ModuleID,
		&i.CreatorUserID,
		&i.Enabled,
		&i.Description,
		&i.TriggerType,
		&i.IntervalSeconds,
		&i.CronExpression,
		&i.Timezone,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.FlowSource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSchedulesByApp = `-- name: GetSchedulesByApp :many
SELECT id, app_id, module_id, creator_user_id, enabled, description, trigger_type, interval_seconds, cron_expression, timezone, next_run_at, last_run_at, flow_source, created_at, updated_at FROM schedules WHERE app_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetSchedulesByApp(ctx context.Context, appID string) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, getSchedulesByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.ModuleID,
			&i.CreatorUserID,
			&i.Enabled,
			&i.Description,
			&i.TriggerType,
			&i.IntervalSeconds,
			&i.CronExpression,
			&i.Timezone,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.FlowSource,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchedule = `-- name: UpdateSchedule :one
UPDATE schedules SET
    enabled = $2,
    description = $3,
    trigger_type = $4,
    interval_seconds = $5,
    cron_expression = $6,
    timezone = $7,
    next_run_at = $8,
    flow_source = $9,
    updated_at = $10
WHERE id = $1 RETURNING id, app_id, module_id, creator_user_id, enabled, description, trigger_type, interval_seconds, cron_expression, timezone, next_run_at, last_run_at, flow_source, created_at, updated_at
`

type UpdateScheduleParams struct {
	ID              string
	Enabled         bool
	Description     string
	TriggerType     string
	IntervalSeconds int32
	CronExpression  string
	Timezone        string
	NextRunAt       pgtype.Timestamp
	FlowSource      []byte
	UpdatedAt       pgtype.Timestamp
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, updateSchedule,
		arg.ID,
		arg.Enabled,
		arg.Description,
		arg.TriggerType,
		arg.IntervalSeconds,
		arg.CronExpression,
		arg.Timezone,
		arg.NextRunAt,
		arg.FlowSource,
		arg.UpdatedAt,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ModuleID,
		&i.CreatorUserID,
		&i.Enabled,
		&i.Description,
		&i.TriggerType,
		&i.IntervalSeconds,
		&i.CronExpression,
		&i.Timezone,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.FlowSource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
