// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_integrations.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookIntegration = `-- name: CreateWebhookIntegration :one
INSERT INTO webhook_integrations (
    id, app_id, type, secret, enabled, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, app_id, type, secret, enabled, created_at, updated_at
`

type CreateWebhookIntegrationParams struct {
	ID        string
	AppID     string
	Type      string
	Secret    string
	Enabled   bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) CreateWebhookIntegration(ctx context.Context, arg CreateWebhookIntegrationParams) (WebhookIntegration, error) {
	row := q.db.QueryRow(ctx, createWebhookIntegration,
		arg.ID,
		arg.AppID,
		arg.Type,
		arg.Secret,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i WebhookIntegration
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Type,
		&i.Secret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhookIntegration = `-- name: DeleteWebhookIntegration :exec
DELETE FROM webhook_integrations WHERE id = $1
`

func (q *Queries) DeleteWebhookIntegration(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteWebhookIntegration, id)
	return err
}

const getWebhookIntegration = `-- name: GetWebhookIntegration :one
SELECT id, app_id, type, secret, enabled, created_at, updated_at
FROM webhook_integrations WHERE id = $1
`

func (q *Queries) GetWebhookIntegration(ctx context.Context, id string) (WebhookIntegration, error) {
	row := q.db.QueryRow(ctx, getWebhookIntegration, id)
	var i WebhookIntegration
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Type,
		&i.Secret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookIntegrationsByApp = `-- name: GetWebhookIntegrationsByApp :many
SELECT id, app_id, type, secret, enabled, created_at, updated_at
FROM webhook_integrations WHERE app_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetWebhookIntegrationsByApp(ctx context.Context, appID string) ([]WebhookIntegration, error) {
	rows, err := q.db.Query(ctx, getWebhookIntegrationsByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookIntegration
	for rows.Next() {
		var i WebhookIntegration
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Type,
			&i.Secret,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhookIntegration = `-- name: UpdateWebhookIntegration :one
UPDATE webhook_integrations SET
    secret = $2,
    enabled = $3,
    updated_at = $4
WHERE id = $1 RETURNING id, app_id, type, secret, enabled, created_at, updated_at
`

type UpdateWebhookIntegrationParams struct {
	ID        string
	Secret    string
	Enabled   bool
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) UpdateWebhookIntegration(ctx context.Context, arg UpdateWebhookIntegrationParams) (WebhookIntegration, error) {
	row := q.db.QueryRow(ctx, updateWebhookIntegration,
		arg.ID,
		arg.Secret,
		arg.Enabled,
		arg.UpdatedAt,
	)
	var i WebhookIntegration
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Type,
		&i.Secret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
